name: base
channels:
  - conda-forge
dependencies:
  - python=3.10
  - conda=
  - conda-libmamba-solver=
  - mamba=
  - pip
  - pre-commit
  - ca-certificates
  - certifi
  - openssl
  - flake8
  - black
  - isort
