name: crossworker
channels:
  - defaults
  - conda-forge
dependencies:
  - websockets
  - loguru
  - python=3.10.6
  - python-dotenv
  - discord.py
  - ca-certificates
  - pip
  - openssl
  - mypy
  - pydantic
  - matplotlib
  - pandas
  - typing
  - pre-commit
  - conda
  - conda-libmamba-solver
  - certifi
  - mamba
