name: crossworker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - mamba
  - discord.py
  - ca-certificates
  - certifi
  - openssl
  - mypy
  - python-socketio
  - python-dotenv
