name: crossworker
channels:
  - conda-forge
dependencies:
  - websockets
  - loguru
  - python=3.10.6
  - python-dotenv
  - discord.py
  - ca-certificates
  - pip
  - openssl
  - mypy
  - pydantic
  - pandas
  - plotly
  - python-kaleido
  - matplotlib
  - celluloid
  - certifi
  - ffmpeg

