name: base
channels:
  - defaults
dependencies:
  - conda
  - openssl
  - python=3.10.6
  - websockets
  - python-dotenv
  - mamba
  - ca-certificates
  - pre-commit
  - pip
  - certifi
  - conda-libmamba-solver
  - mypy
  - loguru
  - discord.py
  - pydantic

