name: crossworker
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.8.5
  - aiosignal=1.3.1
  - async-timeout=4.0.3
  - attrs=23.1.0
  - bidict=0.22.1
  - boltons=23.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - colorama=0.4.6
  - conda=23.7.3
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.3
  - discord.py=2.3.2
  - fmt=10.1.1
  - frozenlist=1.4.0
  - icu=73.2
  - idna=3.4
  - jsonpatch=1.32
  - jsonpointer=2.0
  - krb5=1.21.2
  - libarchive=3.6.2
  - libcurl=8.2.1
  - libcxx=16.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libiconv=1.17
  - libmamba=1.5.1
  - libmambapy=1.5.1
  - libnghttp2=1.52.0
  - libsolv=0.7.24
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libxml2=2.11.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.1
  - multidict=6.0.4
  - mypy=1.5.1
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - openssl=3.1.2
  - packaging=23.1
  - pip=23.2.1
  - pluggy=1.3.0
  - psutil=5.9.5
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.6
  - python-dotenv=1.0.0
  - python-engineio=4.7.0
  - python-socketio=4.6.1
  - python_abi=3.10
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - ruamel.yaml=0.17.32
  - ruamel.yaml.clib=0.2.7
  - setuptools=68.1.2
  - six=1.16.0
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - tqdm=4.66.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=2.0.4
  - websocket-client=0.58.0
  - wheel=0.41.2
  - xz=5.2.6
  - yaml-cpp=0.7.0
  - yarl=1.9.2
  - zstandard=0.19.0
  - zstd=1.5.5
