name: crossworker
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.10.6
  - discord.py
  - loguru
  - ca-certificates
  - openssl
  - websockets
  - python-dotenv
  - mypy
  - pip:
      - cachecontrol==0.13.1
      - cryptography==41.0.3
      - gcloud==0.18.3
      - google-api-core==2.11.1
      - google-api-python-client==2.98.0
      - google-auth==2.23.0
      - google-auth-httplib2==0.1.1
      - google-cloud-core==2.3.3
      - google-cloud-firestore==2.11.1
      - google-cloud-storage==2.10.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.6.0
      - googleapis-common-protos==1.60.0
      - grpcio==1.58.0
      - grpcio-status==1.58.0
      - httplib2==0.22.0
      - jws==0.1.3
      - oauth2client==4.1.3
      - proto-plus==1.22.3
      - protobuf==4.24.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycryptodome==3.18.0
      - pyjwt==2.8.0
      - pyparsing==3.1.1
      - pyrebase4==4.7.1
      - python-jwt==2.0.1
      - requests==2.29.0
      - requests-toolbelt==0.10.1
      - uritemplate==4.1.1
